										-- CANCELLATIONS

-- What percentage of bookings were canceled?

SELECT 
	ROUND(SUM(CASE WHEN CANCELLED = "YES" THEN 1
    ELSE 0 END) * 100 / COUNT(*),2) AS CANCELLATION_PERCENTAGE
FROM hotel_bookings;

-- WHICH COUNTRY HAD THE HIGHEST CANCELLATION RATE ?

SELECT 
	COUNTRY,
    COUNT(*) AS TOTAL_BOOKINGS,
    SUM(CASE WHEN CANCELLED = "YES" THEN 1 ELSE 0 END) AS CANCELLED_BOOKINGS,
	ROUND(SUM(CASE WHEN CANCELLED = "YES" THEN 1 ELSE 0 END) * 100 / COUNT(*), 2) AS CANCELLATION_RATE
FROM hotel_bookings
group by COUNTRY 
HAVING COUNT(*) > 50 
ORDER BY CANCELLATION_RATE desc
LIMIT 10;