                                 -- CUSTOMER SEGMENTATION

-- WHICH MARKET SEGMENT HAS MOST BOOKINGS?

select 
	MARKET_SEGMENT,
    COUNT(*) AS TOTAL_BOOKINGS 
FROM HOTEL_BOOKINGS 
GROUP BY MARKET_SEGMENT 
ORDER BY TOTAL_BOOKINGS DESC;

-- WHICH MARKET SEGMENT HAS THE HIGHEST CANCELLATION RATE?

select 
	MARKET_SEGMENT,
    COUNT(*) AS TOTAL_BOOKINGS,
    SUM(case when CANCELLED = "YES" THEN 1 ELSE 0 END) AS CANCELLED_BOOKINGS,
    ROUND(SUM(CASE WHEN CANCELLED = "YES" THEN 1 ELSE 0 END) * 100 / COUNT(*), 2) AS CANCELLATION_RATE
FROM HOTEL_BOOKINGS 
group by MARKET_SEGMENT
order by CANCELLATION_RATE ;