                              -- REVENUE ANALYSIS 
                              
-- AVERAGE DAILY RATE(ADR) BY HOTEL TYPE 

SELECT 
	HOTEL,
    ROUND(AVG(AVERAGE_DAILY_RATE), 2) AS AVERAGE_ADR
FROM hotel_bookings
WHERE CANCELLED = "NO"
GROUP BY Hotel;

-- MONTHLY REVENUE TRENDS 

SELECT 
	YEAR,
    MONTH,
    ROUND(SUM(AVERAGE_DAILY_RATE), 2) AS TOTAL_REVENUE
FROM hotel_bookings
WHERE CANCELLED = "NO"
GROUP BY YEAR, MONTH 
ORDER BY YEAR, FIELD(MONTH, 'JANUARY', 'FEBRUARY', 'MARCH', 'APRIL', 'MAY', 'JUNE', 'JULY', 'AUGUST',
							'SEPTEMBER', 'OCTOBER', 'NOVEMBER', 'DECEMBER');