                                     -- SEASONALITY
                               
-- WHICH MONTHS SEE THE HIGHEST NUMBER OF BOOKINGS?

SELECT 
	MONTH,
    COUNT(*) AS TOTAL_BOOKINGS
FROM HOTEL_BOOKINGS
group by month
ORDER BY TOTAL_BOOKINGS DESC;

-- WHICH MONTHS HAVE HIGHEST CANCELLATIONS?

SELECT 
	MONTH,
    sum(CASE  WHEN CANCELLED = "YES" THEN 1 ELSE 0 END) AS CANCELLED_BOOKINGS
FROM hotel_bookings
GROUP BY Month
ORDER BY CANCELLED_BOOKINGS DESC;